[project] 
name = "lambda_turn_based_game"
version = "0.1"
description = "Python AWS lambda function that contains game logic"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
